name: Deploy Invoice Extractor via Docker Hub

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: aqiliman24/invoice-extractor
  IMAGE_TAG: latest
  DEPLOY_HOST: ${{ secrets.SERVER_IP }}
  DEPLOY_USER: ${{ secrets.SERVER_USER }}
  DEPLOY_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker logout

      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.DEPLOY_HOST }}
          port: ${{ env.DEPLOY_PORT }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.DEPLOY_SSH_KEY }}
          script: |
            docker pull --quiet ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            docker stop invoice-extractor-container || true
            docker rm invoice-extractor-container || true
            docker run -d \
              --restart unless-stopped \
              --name invoice-extractor-container \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              -p 5050:5050 \
              -e HOST=0.0.0.0 \
              ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
 