name: Invoice Extractor API

permissions:
  contents: read
  packages: write

env:
  DEPLOY_HOST: ${{ secrets.SERVER_IP }}
  DEPLOY_USER: ${{ secrets.SERVER_USER }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout your code
      - uses: actions/checkout@v3

      # 2. Set up SSH key for authentication
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      # 3. Deploy to server via SSH
      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.DEPLOY_USER }}@${{ env.DEPLOY_HOST }} "
            cd ~/invoice-ocr
            git pull origin main
            docker stop invoice-extractor-container || true
            docker rm invoice-extractor-container || true
            docker build -t invoice-extractor .
            docker run -d \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              -e HOST=${{ secrets.HOST }} \
              -p 5050:5050 \
              --name invoice-extractor-container invoice-extractor
          "