name: Invoice Extractor API

permissions:
  contents: read
  packages: write

env:
  DEPLOY_HOST: ${{ secrets.SERVER_IP }}
  DEPLOY_USER: ${{ secrets.SERVER_USER }}
  DEPLOY_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
  DEPLOY_SSH_PASSPHRASE: ${{ secrets.SERVER_SSH_PASSPHRASE }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout your code
      - uses: actions/checkout@v3

      # 2. Deploy to server via SSH using appleboy/ssh-action
      - name: Deploy to remote server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.DEPLOY_SSH_KEY }}
          passphrase: ${{ env.DEPLOY_SSH_PASSPHRASE }}
          port: 22
          script: |
            cd ~/invoice-ocr
            git pull origin main
            docker stop invoice-extractor-container || true
            docker rm invoice-extractor-container || true
            docker build -t invoice-extractor .
            docker run -d \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              -e HOST=${{ secrets.HOST }} \ 
              -p 5050:5050 \
              --name invoice-extractor-container invoice-extractor