name: Deploy Invoice Extractor

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: invoice-extractor
  IMAGE_TAG: latest
  IMAGE_FILE: invoice-extractor.tar
  DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
  DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
  DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Save image to tar file
        run: |
          docker save ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -o ${{ env.IMAGE_FILE }}

      - name: Copy image to server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.DEPLOY_SSH_KEY }}
          source: ${{ env.IMAGE_FILE }}
          target: ~

      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.DEPLOY_SSH_KEY }}
          script: |
            docker load -i ${{ env.IMAGE_FILE }}
            docker stop invoice-extractor-container || true
            docker rm invoice-extractor-container || true
            docker run -d \
              --name invoice-extractor-container \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              -e HOST=${{ secrets.HOST }} \
              -p 5050:5050 \
              ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
